#! /bin/sh
THEANO_FLAGS="device=gpu" ./video_demo.py -m $PYLEARN2_TRAIN_DIR/norb_maxout/norb_maxout_experiments/2014_07_27_0.026_error/norb_small_restart_best.pkl -p $PYLEARN2_DATA_PATH/norb_small/instance_recognition/small_norb_left_02_00_gcn_zca_preprocessor.pkl
